/**
 * Dexo v5 - 01: BusinessTypeTemplate for all 12 domain types
 *
 * Each template configures website sections, onboarding steps,
 * dashboard layout, and feature flags for its industry.
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const TEMPLATES = [
  {
    domainType: 'FITNESS_CENTER',
    icon: '🏋️',
    name: 'Fitness Center',
    description: 'Complete gym and fitness management platform',
    tagline: 'Transform lives, one workout at a time',
    colorPrimary: '#E85D24',
    colorAccent: '#F2A623',
    colorBg: '#0F0F0F',
    websiteSections: {
      hero: { enabled: true, variant: 'video-bg' },
      stats: { enabled: true, items: ['Members', 'Trainers', 'Classes', 'Branches'] },
      services: { enabled: true, label: 'Our Classes' },
      trainers: { enabled: true, label: 'Our Trainers' },
      schedule: { enabled: true },
      pricing: { enabled: true },
      testimonials: { enabled: true },
      gallery: { enabled: true },
      contact: { enabled: true },
      cta: { enabled: true, text: 'Start Your Free Trial' },
    },
    onboardingSteps: [
      { step: 1, title: 'Your gym details', fields: ['name', 'phone', 'address', 'description'] },
      { step: 2, title: 'Choose your services', fields: ['services[]'] },
      { step: 3, title: 'Set membership plans', fields: ['plans[]'] },
      { step: 4, title: 'Upload branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Add your first trainer', fields: ['trainer.name', 'trainer.email', 'trainer.specialization'] },
      { step: 6, title: 'Launch your website', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: {
      widgets: [
        { id: 'active-members', col: 1, row: 1, w: 2, h: 1 },
        { id: 'todays-classes', col: 3, row: 1, w: 2, h: 1 },
        { id: 'revenue-chart', col: 1, row: 2, w: 4, h: 2 },
        { id: 'upcoming-renewals', col: 1, row: 4, w: 2, h: 2 },
        { id: 'trainer-schedule', col: 3, row: 4, w: 2, h: 2 },
      ],
    },
    features: { members: true, trainers: true, classes: true, attendance: true, nutrition: true, pos: true, branches: true, onlineBooking: true },
  },
  {
    domainType: 'RESTAURANT_AND_CAFE',
    icon: '🍽️',
    name: 'Restaurant & Cafe',
    description: 'POS, kitchen, tables, reservations',
    tagline: 'Serve great food, run a great business',
    colorPrimary: '#C0392B',
    colorAccent: '#E67E22',
    colorBg: '#1A0A00',
    websiteSections: {
      hero: { enabled: true, variant: 'full-menu-bg' },
      menu: { enabled: true, label: 'Our Menu' },
      specials: { enabled: true, label: "Today's Specials" },
      reservation: { enabled: true },
      story: { enabled: true, label: 'Our Story' },
      gallery: { enabled: true },
      reviews: { enabled: true },
      contact: { enabled: true },
      cta: { enabled: true, text: 'Reserve a Table' },
    },
    onboardingSteps: [
      { step: 1, title: 'Restaurant details', fields: ['name', 'phone', 'address', 'cuisine'] },
      { step: 2, title: 'Opening hours', fields: ['hours[]'] },
      { step: 3, title: 'Add menu categories', fields: ['menuCategories[]'] },
      { step: 4, title: 'Upload branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Set up tables', fields: ['tableCount', 'tableLayout'] },
      { step: 6, title: 'Launch your restaurant site', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: {
      widgets: [
        { id: 'todays-reservations', col: 1, row: 1, w: 2, h: 1 },
        { id: 'active-orders', col: 3, row: 1, w: 2, h: 1 },
        { id: 'revenue-chart', col: 1, row: 2, w: 4, h: 2 },
        { id: 'table-status', col: 1, row: 4, w: 2, h: 2 },
        { id: 'popular-items', col: 3, row: 4, w: 2, h: 2 },
      ],
    },
    features: { pos: true, orders: true, kitchen: true, tables: true, reservations: true, menu: true, delivery: true, onlineOrdering: true },
  },
  {
    domainType: 'SALON_AND_SPA',
    icon: '💇',
    name: 'Salon & Spa',
    description: 'Appointments, stylists, services',
    tagline: 'Relax. Refresh. Rejuvenate.',
    colorPrimary: '#B76E79',
    colorAccent: '#F5E6D3',
    colorBg: '#FFF8F3',
    websiteSections: { hero: { enabled: true }, services: { enabled: true, label: 'Our Services' }, stylists: { enabled: true, label: 'Our Stylists' }, gallery: { enabled: true }, reviews: { enabled: true }, contact: { enabled: true }, cta: { enabled: true, text: 'Book Appointment' } },
    onboardingSteps: [
      { step: 1, title: 'Salon details', fields: ['name', 'phone', 'address'] },
      { step: 2, title: 'Services', fields: ['services[]'] },
      { step: 3, title: 'Stylists', fields: ['stylists[]'] },
      { step: 4, title: 'Branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Hours', fields: ['hours[]'] },
      { step: 6, title: 'Launch', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: { widgets: [{ id: 'today-appointments', col: 1, row: 1, w: 2, h: 1 }, { id: 'revenue-chart', col: 1, row: 2, w: 4, h: 2 }] },
    features: { appointments: true, stylists: true, services: true, packages: true, loyalty: true },
  },
  {
    domainType: 'HOTEL_AND_HOSPITALITY',
    icon: '🏨',
    name: 'Hotel & Hospitality',
    description: 'Rooms, reservations, housekeeping',
    tagline: 'Your home, away from home',
    colorPrimary: '#1B3A4B',
    colorAccent: '#C9A96E',
    colorBg: '#FAF7F2',
    websiteSections: { hero: { enabled: true }, rooms: { enabled: true, label: 'Our Rooms' }, amenities: { enabled: true }, gallery: { enabled: true }, reviews: { enabled: true }, contact: { enabled: true }, cta: { enabled: true, text: 'Book a Room' } },
    onboardingSteps: [
      { step: 1, title: 'Hotel details', fields: ['name', 'phone', 'address'] },
      { step: 2, title: 'Room types', fields: ['rooms[]'] },
      { step: 3, title: 'Amenities', fields: ['amenities[]'] },
      { step: 4, title: 'Branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Policies', fields: ['checkIn', 'checkOut', 'cancellation'] },
      { step: 6, title: 'Launch', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: { widgets: [{ id: 'occupancy', col: 1, row: 1, w: 2, h: 1 }, { id: 'todays-arrivals', col: 3, row: 1, w: 2, h: 1 }, { id: 'revenue-chart', col: 1, row: 2, w: 4, h: 2 }] },
    features: { rooms: true, reservations: true, housekeeping: true, guests: true },
  },
  {
    domainType: 'HEALTHCARE_CLINIC',
    icon: '🏥',
    name: 'Healthcare Clinic',
    description: 'Patients, doctors, records',
    tagline: 'Compassionate care, modern technology',
    colorPrimary: '#2C7A7B',
    colorAccent: '#81E6D9',
    colorBg: '#F7FAFC',
    websiteSections: { hero: { enabled: true }, services: { enabled: true, label: 'Our Specialties' }, doctors: { enabled: true, label: 'Our Doctors' }, contact: { enabled: true }, cta: { enabled: true, text: 'Book Appointment' } },
    onboardingSteps: [
      { step: 1, title: 'Clinic details', fields: ['name', 'phone', 'address', 'specialty'] },
      { step: 2, title: 'Services', fields: ['services[]'] },
      { step: 3, title: 'Doctors', fields: ['doctors[]'] },
      { step: 4, title: 'Branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Hours', fields: ['hours[]'] },
      { step: 6, title: 'Launch', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: { widgets: [{ id: 'todays-appointments', col: 1, row: 1, w: 2, h: 1 }, { id: 'patient-count', col: 3, row: 1, w: 2, h: 1 }] },
    features: { patients: true, doctors: true, records: true, prescriptions: true, appointments: true },
  },
  {
    domainType: 'SCHOOL_AND_EDUCATION',
    icon: '🏫',
    name: 'School & Education',
    description: 'Students, teachers, classes, exams',
    tagline: 'Building tomorrow, one student at a time',
    colorPrimary: '#3182CE',
    colorAccent: '#F6AD55',
    colorBg: '#FFFAF0',
    websiteSections: { hero: { enabled: true }, programs: { enabled: true, label: 'Our Programs' }, teachers: { enabled: true, label: 'Our Faculty' }, contact: { enabled: true }, cta: { enabled: true, text: 'Apply Now' } },
    onboardingSteps: [
      { step: 1, title: 'School details', fields: ['name', 'phone', 'address'] },
      { step: 2, title: 'Classes', fields: ['classes[]'] },
      { step: 3, title: 'Teachers', fields: ['teachers[]'] },
      { step: 4, title: 'Branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Academic year', fields: ['sessions[]'] },
      { step: 6, title: 'Launch', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: { widgets: [{ id: 'student-count', col: 1, row: 1, w: 2, h: 1 }, { id: 'attendance', col: 3, row: 1, w: 2, h: 1 }] },
    features: { students: true, teachers: true, classes: true, exams: true, grading: true },
  },
  {
    domainType: 'COACHING_INSTITUTE',
    icon: '🎓',
    name: 'Coaching Institute',
    description: 'Batches, courses, mock tests, results',
    tagline: 'Excel with expert guidance',
    colorPrimary: '#553C9A',
    colorAccent: '#FBB6CE',
    colorBg: '#FAF5FF',
    websiteSections: { hero: { enabled: true }, courses: { enabled: true, label: 'Our Courses' }, results: { enabled: true, label: 'Top Results' }, faculty: { enabled: true, label: 'Our Faculty' }, contact: { enabled: true }, cta: { enabled: true, text: 'Enroll Now' } },
    onboardingSteps: [
      { step: 1, title: 'Institute details', fields: ['name', 'phone', 'address'] },
      { step: 2, title: 'Courses', fields: ['courses[]'] },
      { step: 3, title: 'Batches', fields: ['batches[]'] },
      { step: 4, title: 'Branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Faculty', fields: ['faculty[]'] },
      { step: 6, title: 'Launch', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: { widgets: [{ id: 'active-batches', col: 1, row: 1, w: 2, h: 1 }, { id: 'recent-results', col: 3, row: 1, w: 2, h: 1 }] },
    features: { students: true, batches: true, courses: true, mockTests: true, results: true },
  },
  {
    domainType: 'ECOMMERCE',
    icon: '🛒',
    name: 'Ecommerce',
    description: 'Products, orders, shipping',
    tagline: 'Shop smarter, live better',
    colorPrimary: '#2D3748',
    colorAccent: '#ED8936',
    colorBg: '#FFFFFF',
    websiteSections: { hero: { enabled: true }, featured: { enabled: true, label: 'Featured Products' }, categories: { enabled: true, label: 'Categories' }, contact: { enabled: true }, cta: { enabled: true, text: 'Shop Now' } },
    onboardingSteps: [
      { step: 1, title: 'Store details', fields: ['name', 'phone', 'address'] },
      { step: 2, title: 'Categories', fields: ['categories[]'] },
      { step: 3, title: 'Products', fields: ['products[]'] },
      { step: 4, title: 'Branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Shipping', fields: ['zones[]'] },
      { step: 6, title: 'Launch', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: { widgets: [{ id: 'orders-today', col: 1, row: 1, w: 2, h: 1 }, { id: 'top-products', col: 3, row: 1, w: 2, h: 1 }] },
    features: { products: true, categories: true, orders: true, inventory: true, shipping: true },
  },
  {
    domainType: 'LOGISTICS_AND_DELIVERY',
    icon: '🚚',
    name: 'Logistics & Delivery',
    description: 'Shipments, fleet, drivers, tracking',
    tagline: 'Move faster, deliver smarter',
    colorPrimary: '#2B6CB0',
    colorAccent: '#F6E05E',
    colorBg: '#F7FAFC',
    websiteSections: { hero: { enabled: true }, services: { enabled: true, label: 'Our Services' }, tracking: { enabled: true }, contact: { enabled: true }, cta: { enabled: true, text: 'Track Shipment' } },
    onboardingSteps: [
      { step: 1, title: 'Company details', fields: ['name', 'phone', 'address'] },
      { step: 2, title: 'Service zones', fields: ['zones[]'] },
      { step: 3, title: 'Fleet', fields: ['vehicles[]'] },
      { step: 4, title: 'Branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Rates', fields: ['rates[]'] },
      { step: 6, title: 'Launch', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: { widgets: [{ id: 'active-shipments', col: 1, row: 1, w: 2, h: 1 }, { id: 'fleet-status', col: 3, row: 1, w: 2, h: 1 }] },
    features: { shipments: true, fleet: true, drivers: true, routes: true, tracking: true },
  },
  {
    domainType: 'TAILOR_SHOP',
    icon: '🧵',
    name: 'Tailor Shop',
    description: 'Customers, measurements, orders',
    tagline: 'Crafted just for you',
    colorPrimary: '#744210',
    colorAccent: '#D69E2E',
    colorBg: '#FFFFF0',
    websiteSections: { hero: { enabled: true }, services: { enabled: true, label: 'Our Services' }, gallery: { enabled: true, label: 'Our Work' }, contact: { enabled: true }, cta: { enabled: true, text: 'Book Measurement' } },
    onboardingSteps: [
      { step: 1, title: 'Shop details', fields: ['name', 'phone', 'address'] },
      { step: 2, title: 'Services', fields: ['services[]'] },
      { step: 3, title: 'Fabrics', fields: ['fabrics[]'] },
      { step: 4, title: 'Branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Pricing', fields: ['rates[]'] },
      { step: 6, title: 'Launch', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: { widgets: [{ id: 'active-orders', col: 1, row: 1, w: 2, h: 1 }, { id: 'delivery-queue', col: 3, row: 1, w: 2, h: 1 }] },
    features: { customers: true, measurements: true, orders: true, fabrics: true, production: true },
  },
  {
    domainType: 'NGO',
    icon: '❤️',
    name: 'Non-Profit',
    description: 'Donors, campaigns, projects, volunteers',
    tagline: 'Together, we make a difference',
    colorPrimary: '#2F855A',
    colorAccent: '#F6E05E',
    colorBg: '#F0FFF4',
    websiteSections: { hero: { enabled: true }, campaigns: { enabled: true, label: 'Active Campaigns' }, impact: { enabled: true }, volunteers: { enabled: true }, contact: { enabled: true }, cta: { enabled: true, text: 'Donate Now' } },
    onboardingSteps: [
      { step: 1, title: 'Organization details', fields: ['name', 'phone', 'address', 'mission'] },
      { step: 2, title: 'Campaigns', fields: ['campaigns[]'] },
      { step: 3, title: 'Projects', fields: ['projects[]'] },
      { step: 4, title: 'Branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Volunteers', fields: ['roles[]'] },
      { step: 6, title: 'Launch', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: { widgets: [{ id: 'donations-month', col: 1, row: 1, w: 2, h: 1 }, { id: 'active-campaigns', col: 3, row: 1, w: 2, h: 1 }] },
    features: { donors: true, campaigns: true, projects: true, volunteers: true },
  },
  {
    domainType: 'SME_CORPORATE',
    icon: '🏢',
    name: 'SME / Corporate',
    description: 'CRM, HR, projects, finance, payroll',
    tagline: 'Run your business, all in one place',
    colorPrimary: '#1A365D',
    colorAccent: '#3182CE',
    colorBg: '#F7FAFC',
    websiteSections: { hero: { enabled: true }, services: { enabled: true, label: 'Our Solutions' }, case_studies: { enabled: true }, contact: { enabled: true }, cta: { enabled: true, text: 'Request Demo' } },
    onboardingSteps: [
      { step: 1, title: 'Company details', fields: ['name', 'phone', 'address', 'industry'] },
      { step: 2, title: 'Departments', fields: ['departments[]'] },
      { step: 3, title: 'Roles', fields: ['roles[]'] },
      { step: 4, title: 'Branding', fields: ['logo', 'coverImage'] },
      { step: 5, title: 'Integrations', fields: ['integrations[]'] },
      { step: 6, title: 'Launch', fields: ['subdomain', 'customDomain'] },
    ],
    dashboardLayout: { widgets: [{ id: 'revenue-month', col: 1, row: 1, w: 2, h: 1 }, { id: 'team-size', col: 3, row: 1, w: 2, h: 1 }, { id: 'project-status', col: 1, row: 2, w: 4, h: 2 }] },
    features: { crm: true, hr: true, projects: true, finance: true, payroll: true },
  },
];

export async function seed01Templates() {
  console.log('  → 01-domain-templates');
  for (const t of TEMPLATES) {
    await prisma.businessTypeTemplate.upsert({
      where: { domainType: t.domainType as any },
      update: t,
      create: t as any,
    });
  }
  console.log(`    seeded ${TEMPLATES.length} templates`);
}

if (require.main === module) {
  seed01Templates()
    .then(() => process.exit(0))
    .catch((e) => { console.error(e); process.exit(1); });
}
