/**
 * nginx-tenant-sync — generates one nginx config fragment per VERIFIED custom
 * domain, so tenant routing stays fully dynamic:
 *
 *   - Platform subdomains (<t>.onedexo.com, admin.<t>., portal.<t>.) need NO
 *     config at all — the wildcard server blocks in infra/nginx/dexo.conf
 *     match every provisioned tenant automatically.
 *   - Custom domains (fitness.com) each get their own fragment in
 *     OUT_DIR (/etc/nginx/dexo-tenants) with their own SSL cert. Re-running
 *     this script rewrites ONLY fragments whose content changed ("fractional"
 *     rebuild), removes fragments for deleted/unverified domains, then
 *     gracefully reloads nginx.
 *
 * Usage (on the VM, after a tenant verifies a domain, or via cron):
 *   npx ts-node scripts/nginx-tenant-sync.ts                # sync + reload
 *   npx ts-node scripts/nginx-tenant-sync.ts --dry-run      # print, no writes
 *   OUT_DIR=/etc/nginx/dexo-tenants CERTBOT=1 npx ts-node scripts/nginx-tenant-sync.ts
 *
 * With CERTBOT=1 it also requests a Let's Encrypt cert (HTTP-01 webroot
 * /var/www/certbot) for any domain that doesn't have one yet.
 */
import { PrismaClient } from '@prisma/client';
import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const prisma = new PrismaClient();
const OUT_DIR = process.env.OUT_DIR || '/etc/nginx/dexo-tenants';
const DRY = process.argv.includes('--dry-run');
const USE_CERTBOT = process.env.CERTBOT === '1';

function fragmentFor(domain: string, slug: string): string {
  const cert = `/etc/letsencrypt/live/${domain}`;
  return `# AUTO-GENERATED by scripts/nginx-tenant-sync.ts — do not edit.
# Tenant: ${slug} · Domain: ${domain}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${domain} www.${domain};

    ssl_certificate     ${cert}/fullchain.pem;
    ssl_certificate_key ${cert}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    client_max_body_size 100M;

    location / {
        proxy_pass         http://dexo_tenant_website;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Tenant-Slug     ${slug};
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        $connection_upgrade;
    }
}
`;
}

async function main() {
  // Verified lifecycle custom domains + legacy Tenant.domain column.
  const lifecycles = await prisma.tenantLifecycle.findMany({
    where: { customDomainVerified: true, customDomain: { not: null } },
    select: { customDomain: true, tenant: { select: { subdomain: true, status: true } } },
  });
  const legacy = await prisma.tenant.findMany({
    where: { domain: { not: null }, status: 'active' },
    select: { domain: true, subdomain: true },
  });

  const domains = new Map<string, string>(); // domain -> slug
  for (const lc of lifecycles) {
    if (lc.customDomain && lc.tenant?.subdomain && lc.tenant.status === 'active') {
      domains.set(lc.customDomain.toLowerCase(), lc.tenant.subdomain);
    }
  }
  for (const t of legacy) {
    if (t.domain && t.subdomain) domains.set(t.domain.toLowerCase(), t.subdomain);
  }

  console.log(`Found ${domains.size} verified custom domain(s).`);
  if (!DRY) fs.mkdirSync(OUT_DIR, { recursive: true });

  let changed = 0;
  const wanted = new Set<string>();
  for (const [domain, slug] of domains) {
    const file = path.join(OUT_DIR, `${slug}--${domain.replace(/[^a-z0-9.-]/g, '')}.conf`);
    wanted.add(path.basename(file));
    const body = fragmentFor(domain, slug);

    if (USE_CERTBOT && !DRY && !fs.existsSync(`/etc/letsencrypt/live/${domain}`)) {
      console.log(`  certbot: issuing cert for ${domain}…`);
      try {
        execSync(`certbot certonly --webroot -w /var/www/certbot -d ${domain} -d www.${domain} -n --agree-tos --register-unsafely-without-email`, { stdio: 'inherit' });
      } catch {
        console.warn(`  ! cert issue failed for ${domain} — fragment skipped (fallback vhost still serves it).`);
        continue;
      }
    }

    const existing = !DRY && fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (existing === body) continue; // unchanged — fractional rebuild skips it
    changed++;
    console.log(`  ${existing === null ? 'create' : 'update'}: ${file}`);
    if (!DRY) fs.writeFileSync(file, body);
  }

  // Remove fragments for domains that no longer exist / were unverified.
  if (!DRY && fs.existsSync(OUT_DIR)) {
    for (const f of fs.readdirSync(OUT_DIR)) {
      if (f.endsWith('.conf') && !wanted.has(f)) {
        console.log(`  remove: ${path.join(OUT_DIR, f)}`);
        fs.unlinkSync(path.join(OUT_DIR, f));
        changed++;
      }
    }
  }

  if (changed === 0) {
    console.log('No changes — nginx reload skipped.');
    return;
  }
  if (DRY) {
    console.log(`[dry-run] ${changed} fragment(s) would change.`);
    return;
  }
  console.log('Validating and reloading nginx…');
  execSync('nginx -t', { stdio: 'inherit' });
  execSync('nginx -s reload', { stdio: 'inherit' });
  console.log('Done.');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
